### ISSUE TITLE
自定义LoadingCallback

### ISSUE THREAD

**Issue by xiellml** [KingJA/LoadSir#10]
更换动画似乎没提供接口

**Comment by KingJA** [comment]
@sieml 你好，不太理解你的意思，你是指要自定义一个进度动画页面吗？能否描述更具体些。

**Comment by xiellml** [comment]
@KingJA 假如我想把ProgressBar换成ImageView的, 使用帧动画. 这时要通过findViewById来找到这个View, 然后开启动画, 还有关闭动画 ,  需要另外处理, 能封装在库中吗? 还是已经有了

**Comment by toothwind** [comment]
1.可以尝试在Callback类添加   
 protected void initView(Context context, View view){
        //do nothing
 }
2.在rootView = View.inflate(context, onCreateView(), null);之后调用;
    public View getRootView() {
        int resId = onCreateView();
        if (resId == 0 && rootView != null) {
            return rootView;
        }
        rootView = View.inflate(context, onCreateView(), null);
        rootView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if (onRetry(context, rootView)) {
                    return;
                }
                if (onReloadListener != null) {
                    onReloadListener.onReload(v);
                }
            }
        });
        initView(context, rootView);
        return rootView;
    }
3.然后在自定义的LoadingCallback重写父类的initView;
public class LoadingCallback extends Callback {

    @Override
    protected int onCreateView() {
        return R.layout.layout_loading;
    }

    @Override
    protected void initView(Context context, View view) {
        super.initView(context, view);
        ImageView ivLoading = (ImageView) view.findViewById(R.id.iv_loading);
        Animation animation = new RotateAnimation(0, 359,Animation.RELATIVE_TO_SELF,
                0.5f,Animation.RELATIVE_TO_SELF,0.5f);
        animation.setDuration(500);
        animation.setRepeatCount(Integer.MAX_VALUE);
        animation.setFillAfter(true);
        ivLoading.startAnimation(animation);//开始动画
    }

}

**Comment by KingJA** [comment]
@sieml 非常好的使用场景，目前LoadSir没有针对该场景的相关API。下个版本会增加。@toothwind 感谢你建议，我想我会在下个版本增加相关API。

**Comment by KingJA** [comment]
@sieml @toothwind 感谢两位的支持，https://github.com/KingJA/LoadSir/blob/v1.2.2-pre/app/src/main/java/sample/kingja/loadsir/callback/AnimateCallback.java LoadSir v1.2.2-pre 更新API，近期将出release版本，欢迎提出意见和建议。
