### ISSUE TITLE
如果绑定的view 不是跟布局 并且有位置信息  不在线性布局中 view 就有可能显示不出来

### ISSUE THREAD

**Issue by wilder-ness** [KingJA/LoadSir#100]
如果绑定的view 不是跟布局 并且有位置信息  不在线性布局中 view 就有可能显示不出来

例如 绑定的view 是一个在约束性布局中的子view 
并且有位置信息 当加载完成调用showSuccess时这个子view 并不能 正确的显示出来 
但是如果是在线性布局中有可能成功。

**Comment by KingJA** [comment]
@guoleifei 你好，约束性布局暂不支持，但在计划中，后续会考虑进行支持。

**Comment by wilder-ness** [comment]
能否变成 替换回来的时候使用原来的布局 不再原有基础上包装一层。只是替换 并不嵌套。

**Comment by ghost** [comment]
你好，什么时候能支持ConstraintLayout？

**Comment by KingJA** [comment]
@guoleifei 你好，1.3.8版已经支持Constraintlayout，具体请看sample及更新说明，欢迎更新，多提宝贵意见:ghost:
