### ISSUE TITLE
能不能添加一个 是否遮罩在原始布局上层这么一个开关

### ISSUE THREAD

**Issue by liuyouth** [KingJA/LoadSir#101]
现在需求 是 点击按钮请求网络 然后弹框 ， 请求网络这个不想用阻塞式 但是还想给用户展示我正在加载，也是为了屏蔽掉重复请求网络的情况，
只是在某个按钮上显示loading 其他view 不受影响 
不算 issue

**Comment by KingJA** [comment]
@liuyouth 你好，LoasSir更适合整个页面或者某个控件和状态页进行整体替换。你所描述的场景只是在按钮上显示loading，你可能需要类似https://github.com/dmytrodanylyk/android-process-button 的库。
