### ISSUE TITLE
如何在特定的CallBack下才执行onReload方法，而不是当前显示那个CallBack然后点击之后就执行onReload

### ISSUE THREAD

**Issue by mrchenmo** [KingJA/LoadSir#103]

**Comment by KingJA** [comment]
@mrchenmo 继承Callback实现onReloadEvent(final Context context, View view)方法，如果放回true则只执行onReloadEvent的逻辑，返回false则同时执行OnReloadListener的onReload(View v)方法

**Comment by mrchenmo** [comment]
@KingJA 收到。
