### ISSUE TITLE
用到RecyclerView的时候 不能显示

### ISSUE THREAD

**Issue by 1izheng** [KingJA/LoadSir#104]
```

<com.scwang.smartrefresh.layout.SmartRefreshLayout
        android:id="@+id/refreshLayout"
        xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        >

        <android.support.v7.widget.RecyclerView
            android:id="@+id/recyclerview"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            />

    </com.scwang.smartrefresh.layout.SmartRefreshLayout>


```
这种布局 我不管是注册到refreshLayout还是注册到recyclerView都是无法显示的。

**Comment by wangkunlin** [comment]
我也是这样用的，也是不显示。

**Comment by wangkunlin** [comment]
```java
mLoadService = new LoadSir.Builder()
        .addCallback(new EmptyCallback(R.drawable.common_icon_error_page, getString(R.string.base_empty_msg)))
        .addCallback(new LoadingCallback())
        .setDefaultCallback(SuccessCallback.class)
        .build()
        .register(mShowDetailRv);

mRefreshLayout.removeView(mLoadService.getLoadLayout());
mRefreshLayout.setRefreshContent(mLoadService.getLoadLayout());
```
我是这样解决的。因为下拉刷新控件它给 RefreshContent 做了包装。所以出了问题

**Comment by 1izheng** [comment]
> ```java
> mLoadService = new LoadSir.Builder()
>         .addCallback(new EmptyCallback(R.drawable.common_icon_error_page, getString(R.string.base_empty_msg)))
>         .addCallback(new LoadingCallback())
>         .setDefaultCallback(SuccessCallback.class)
>         .build()
>         .register(mShowDetailRv);
> 
> mRefreshLayout.removeView(mLoadService.getLoadLayout());
> mRefreshLayout.setRefreshContent(mLoadService.getLoadLayout());
> ```
> 
> 我是这样解决的。因为下拉刷新控件它给 RefreshContent 做了包装。所以出了问题

这么搞太烦躁了 我直接外层又套了一层布局 就完事了。。

**Comment by wangkunlin** [comment]
@1izheng 嗯，都可以。我不想套。所以手动移除再添加一下。

**Comment by feishuixiansheng** [comment]
我的根布局是一个LinearLayout，RecyclerView权重设为1，下面还有一个按钮，不能显示，我又给RecyclerView套了一层LinearLayout，还是不成功，是应该怎么修改？

**Comment by liuxuwei** [comment]
我在外层又加了一个LinearLayout也是不显示

**Comment by liuxuwei** [comment]
<com.scwang.smartrefresh.layout.SmartRefreshLayout
        android:id="@+id/smart_examine_refresh"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_below="@id/ll_btn_date">

        <RelativeLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent">

            <android.support.v7.widget.RecyclerView
                android:id="@+id/rcy_examine_list"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:layout_marginTop="@dimen/dp_15" />
        </RelativeLayout>

    </com.scwang.smartrefresh.layout.SmartRefreshLayout>

这样嵌套可以显示
