### ISSUE TITLE
大大，你好，我viewpage+frgament 进行状态页切换问题（已用demo 的用法，还是有问题）

### ISSUE THREAD

**Issue by xyZangGit** [KingJA/LoadSir#107]
这是我的viewpageadapter的写法
![adapters](https://user-images.githubusercontent.com/19574114/50416806-94075500-085d-11e9-8b7c-a9c7b41f47e7.png)
这是我请求frgament的写法
1： 这个是无数据的写法：
           mBaseLoadService.setCallBack(EmptyCallback.class, this);
            PostUtil.postCallbackDelayed(mBaseLoadService, EmptyCallback.class);
2：这个是有数据的写法：
 PostUtil.postSuccessDelayed(mBaseLoadService);
3：这个是加载出错的写法（无网络）
mBaseLoadService.showCallback(ErrorCallback.class);

是viewpage+3个fragment
左右滑动 frgamnet，第三个frgament第一次可以加载出来数据，再次滑动到第三个frgament的时候页面就是白页，没有数据的，
希望大大可以看看是什么问题

**Comment by KingJA** [comment]
@xyZangGit 你好，尝试FragmentStatePagerAdapter试下，或者FragmentPagerAdapter预加载3全部Fragment。

**Comment by xyZangGit** [comment]
> @xyZangGit 你好，尝试FragmentStatePagerAdapter试下，或者FragmentPagerAdapter预加载3全部Fragment。

FragmentStatePagerAdapter 是没问题的，但是左右切换每次都要显示加载的页面不太好，有其他解决方案么

**Comment by KingJA** [comment]
@xyZangGit 你好，可以预加载全部页并且只加载一次。具体实现你可以搜索下。

**Comment by xyZangGit** [comment]
> @xyZangGit 你好，可以预加载全部页并且只加载一次。具体实现你可以搜索下。

如果分类特别的多，比如 15个分类，全部预加载肯定不行吧
