### ISSUE TITLE
EmptyCallback中textview不能传递值

### ISSUE THREAD

**Issue by wms1993** [KingJA/LoadSir#11]
比如我现在加载的页面要显示列表不能为空，另外一个界面显示消息不能为空，但是这个页面就一个文字不一样，我不能传递字符串过去，这个问题怎么解决？

**Comment by KingJA** [comment]
@wms1993 你好，很好的场景。可以让子弹先飞会，看看有没童鞋能解决这个问题。如果你这个需求属于特例的话，我建议加两个Callback。

**Comment by KingJA** [comment]
@wms1993 你好，我正在整理目前的issues和建议，如果需求多的话，我会在下个版本完善这个功能。如果有其它建议，欢迎提出。

**Comment by KingJA** [comment]
@wms1993 你好，新版本增加了该功能，https://github.com/KingJA/LoadSir/blob/v1.2.2-pre/app/src/main/java/sample/kingja/loadsir/target/NormalActivity.java#L58-L64
可通过预览版尝试，https://github.com/KingJA/LoadSir/tree/v1.2.2-pre
，欢迎提出意见和建议。
