### ISSUE TITLE
现在点击重试的事件，是在整个页面中。怎么实现点击Error视图中的某个控件来重试

### ISSUE THREAD

**Issue by FunnyLee** [KingJA/LoadSir#112]
如果在ErrorCallback中重写onReloadEvent方法，这样不是很好封装，没办法写入基类里面。

**Comment by KingJA** [comment]
@FunnyLee 你好
1.怎么实现点击Error视图中的某个控件来重试？
可以直接注册View或者onReloadEvent中获取某个空间的id再实现点击逻辑。
2.在ErrorCallback中重写onReloadEvent方法，这样不是很好封装，没办法写入基类里面？
可以在基类容器抽象出方法，然后给子类实现。但是目前无法判断是点击的是哪个Callback，后期将将入ResultCode来区别各个Callback。
