### ISSUE TITLE
网络好的时候也会看到动画很长时间，怎么解决？

### ISSUE THREAD

**Issue by lbx2015** [KingJA/LoadSir#113]
不用LoadService很快，无感的，用了就会看到加载动画，怎么办？

**Comment by lbx2015** [comment]
不是这个问题，我发现是我用的SmartRefresh的问题。好像有一闪，有延迟1秒在显示加载动画的设置吗？或者默认有延迟吗？

**Comment by KingJA** [comment]
@lbx2015 你好，默认没有延迟。
