### ISSUE TITLE
在BaseFragment中初始化LoadSir

### ISSUE THREAD

**Issue by guozhiqiang123** [KingJA/LoadSir#114]
有多个同级加载的fragment,并且这每一个fragment都有自己绘制的toolbar,每一个fragment都继承自BaseFragment（主页面底部四个按钮，上面四个fragment的情况），运行的时候就会报java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
这种情况该怎么解决？

**Comment by KingJA** [comment]
@guozhiqiang123 你好，给出的信息不足，无法给出判断。建议先参考Demo里关于多Fragment注册的代码实例。

**Comment by magic0908** [comment]
@guozhiqiang123  
我猜你是没有移除子view的parent，可以试试这么写
![image](https://user-images.githubusercontent.com/23170601/73326573-9b353980-428d-11ea-90be-19f237bf5d5a.png)
