### ISSUE TITLE
Error:(119, 38) 警告: [unchecked] 对作为原始类型LoadService的成员的showCallback(Class<? extends Callback>)的调用未经过检查

### ISSUE THREAD

**Issue by puxiaoshuai** [KingJA/LoadSir#116]
Error:(119, 38) 警告: [unchecked] 对作为原始类型LoadService的成员的showCallback(Class<? extends Callback>)的调用未经过检查

**Comment by KingJA** [comment]
@puxiaoshuai 你好，提供的信息不够详细，无法做出判断。
