### ISSUE TITLE
SmartRefreshLayout  嵌套recycleview  替换recycleview  不显示问题，必须在嵌套一层RelativeLayout（已看问题#104）

### ISSUE THREAD

**Issue by xyZangGit** [KingJA/LoadSir#117]
<com.scwang.smartrefresh.layout.SmartRefreshLayout
        android:id="@+id/refreshLayout"
        xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        >

        <android.support.v7.widget.RecyclerView
            android:id="@+id/recyclerview"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            />

    </com.scwang.smartrefresh.layout.SmartRefreshLayout>

上面是有问题的替换布局

改成下面的布局 就没有问题了
<com.scwang.smartrefresh.layout.SmartRefreshLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/my_activities_smartRefreshLayout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/white"
    tools:context=".activity.MyActivitiesActivity">

    <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <android.support.v7.widget.RecyclerView
            android:id="@+id/my_activities_recycleview"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />
    </RelativeLayout>
</com.scwang.smartrefresh.layout.SmartRefreshLayout>

这样多嵌套一层是不太好的，希望两位大大能结合解决一下这个问题，不然只能抛弃其中一个库使用了，这让我很痛苦，这个问题我同样反馈给了smart控件的大大了

**Comment by KingJA** [comment]
@xyZangGit 你好，请在issures搜索下SmartRefreshLayout ，看看现有的解决方案能否解决你的问题。

**Comment by xyZangGit** [comment]
我找到了解决方案，但是要再嵌套一层相对布局，这样不太好啊，有没有办法解决，不在嵌套一层

**Comment by KingJA** [comment]
@xyZangGit 你好，暂时没有更好的方法，因为和SmartRefreshLayout 的底层代码有些不兼容，以前联系过SmartRefreshLayout的作者，在某个版本进行了兼容，后续版本有没兼容不知。
