### ISSUE TITLE
在View中使用时,margin变大的bug

### ISSUE THREAD

**Issue by xiaobug0929** [KingJA/LoadSir#121]
loassir在view中使用时,当view本身设置了margin值时,在7.0及以上版本会出现以下问题:

loadsir在设置loadlayout时,会将view本身的layoutparams属性添加到自己身上,
而在切换为成功状态时,由于view本身也具有margin值,所有看起来view的margin值会变大一倍,

该问题在6.0及以下版本上,只有父容器为FrameLayout时才会复现,

由此推断,应该是高版本系统修改了addView源码中关于LayoutParams的相关部分,具体问题没有对比源码进行排查,我自己解决的方法是在SuccessCallback的构造方法中对view的LayoutParams进行重新赋值,
目前只测试了margin和padding,其他属性因为项目中没有涉及到所有没有测试,希望作者继续完善,最后,开源万岁

 public SuccessCallback(View view, Context context, OnReloadListener onReloadListener) {
        super(view, context, onReloadListener);
        view.setLayoutParams(new ViewGroup.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT));
    }

**Comment by KingJA** [comment]
@xiaobug0929 1.3.8版已经支持修复该问题，欢迎更新，感谢你的使用:ghost:
