### ISSUE TITLE
库什么时候能支持ConstraintLayout

### ISSUE THREAD

**Issue by MakeCodeFly** [KingJA/LoadSir#124]

**Comment by zhuzheng1991** [comment]
是的 希望加入对constraintlayout的支持 在对constraintlayout里面的view进行替换 会不显示控件

**Comment by KingJA** [comment]
@MakeCodeFly @zhuzheng1991 各位好，1.3.8版已经支持Constraintlayout，具体请看sample及更新说明，欢迎更新，多提宝贵意见:ghost:
