### ISSUE TITLE
好像是加载不了AndroidX的Fragment。

### ISSUE THREAD

**Issue by taozhixiang** [KingJA/LoadSir#126]
我把项目升级到AndroidX之后。frament显示不出来了。

**Comment by shenqinwei** [comment]
我也是这样，升级了Androidx,就加载不出来了

**Comment by wenshuo001** [comment]
作者应该是还没有兼容 Androidx

**Comment by fubd** [comment]
有解决方案吗? 在BaseFragment的·onCreateView中 绑定loadsir，继承了SupportFragment,看了下fragmentation引入的是androix.fargment。导致fragment没显示出来 @KingJA

**Comment by Jiabaokang** [comment]
override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?): View? {
        val rootView = inflater.inflate(R.layout.fragment_reservation_car_list,container,false)
        mLoadSir = LoadSir.getDefault().register(rootView.findViewById(R.id.smartRefreshLayout)){
            mLoadSir.showCallback(LoadingCallback::class.java)
            refreshData()
        }
        return mLoadSir.loadLayout
    }
最后一行很重要mLoadSir.loadLayout，在AndroidX中使用没有问题

**Comment by KingJA** [comment]
@taozhixiang @shenqinwei @wenshuo001 @fubd @Jiabaokang 各位好，1.3.8版已经支持Androidx，欢迎更新，多提宝贵意见:ghost:

**Comment by xyZangGit** [comment]
> @taozhixiang @shenqinwei @wenshuo001 @fubd @Jiabaokang 各位好，1.3.8版已经支持Androidx，欢迎更新，多提宝贵意见👻

已经升级到1.3.8，也升级了ANDROIDX，导致frgament加载不出来，和楼上的用法都一样

**Comment by xyZangGit** [comment]
> @taozhixiang @shenqinwei @wenshuo001 @fubd @Jiabaokang 各位好，1.3.8版已经支持Androidx，欢迎更新，多提宝贵意见👻

已经升级到1.3.8，也升级了ANDROIDX，导致frgament加载不出来，和楼上的用法都一样，一直在 loading页面，调用mBaseLoadService.showSuccess();无效，
jietu截图是我的代码，迁移androidX之前是没有问题的，其他也没有问题，
![image](https://user-images.githubusercontent.com/19574114/77739900-46bff780-704d-11ea-8812-32e7f13aa650.png)

**Comment by KingJA** [comment]
@xyZangGit 你好，1.3.8的案例里都是androidx的Fragment，你可以参考下。你提供的代码没有上下文，看不出问题，如果还有问题能否提供一个发生问题的类似demo : )

**Comment by xyZangGit** [comment]
> @xyZangGit 你好，1.3.8的案例里都是androidx的Fragment，你可以参考下。你提供的代码没有上下文，看不出问题，如果还有问题能否提供一个发生问题的类似demo : )

四个fragment，同样的写法2个加载出来，2个不能加载出来，再移植到androidX以后 出现的这个问题，我尝试不替换rootview，而是直接替换某个根view是没问题的

**Comment by KingJA** [comment]
@xyZangGit 很高兴你暂时解决了这个问题。我刚建了QQ群818251143，如果你想进一步解决这个问题的话，可以在里面沟通。
