### ISSUE TITLE
fragment的布局中含有scrollview加载不出来

### ISSUE THREAD

**Issue by wuh876** [KingJA/LoadSir#129]
ScrollView xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:descendantFocusability="blocksDescendants"
    android:fillViewport="true"
    android:scrollbars="none">

    <LinearLayout
        android:id="@+id/layout_web"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical">

        <com.MyWebview
            android:id="@+id/webView"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />
    </LinearLayout>
</ScrollView>

loadService = LoadSir.getDefault().register(layout_web, new Callback.OnReloadListener() {
            @Override
            public void onReload(View v) {
               
            }
        });

**Comment by KingJA** [comment]
@wuh876 你好，可以尝试在ScrollView外层套一层布局，在这层布局上注册。
