### ISSUE TITLE
切换的视图为SmartRefreshLayout里的listview会报错

### ISSUE THREAD

**Issue by Suguiqiang** [KingJA/LoadSir#13]
java.lang.ClassCastException: android.widget.FrameLayout$LayoutParams cannot be cast to com.scwang.smartrefresh.layout.SmartRefreshLayout$LayoutParams

**Comment by KingJA** [comment]
@Suguiqiang 你好，能否提供完整的代码，或者Demo.zip发我gmail。

**Comment by Suguiqiang** [comment]
谢谢，我整理下发给您。

**Comment by KingJA** [comment]
@Suguiqiang 已回复邮箱
