### ISSUE TITLE
ViewPager2上拉加载问题

### ISSUE THREAD

**Issue by KarenKaKa** [KingJA/LoadSir#135]
fragment对照例子写的，ViewPager使用没问题，ViewPager2上拉加载的时候FooterView显示在列表上而不是随着列表上拉出来的

**Comment by KingJA** [comment]
@KarenKaKa 你好，我需要更详细的信息，最好提供可运行的代码，这样问题解决效率会高点。

**Comment by liudaohong** [comment]
可以直接在状态页最外层加nestscrollview  看下

**Comment by YaraKaKa** [comment]
> 可以直接在状态页最外层加nestscrollview 看下

并没有好的效果
