### ISSUE TITLE
 LoadLayout类中   Callback cloneCallback = callback.copy(); 为什么要copy callback的实现类啊？

### ISSUE THREAD

**Issue by itsnicerdx** [KingJA/LoadSir#137]
不理解为什么要copy一个Callback实现类对象放入 HashMap

**Comment by KingJA** [comment]
@itsnicerdx 你好，请参考
[issues/76](https://github.com/KingJA/LoadSir/issues/76)
[issues/32](https://github.com/KingJA/LoadSir/issues/32)

**Comment by itsnicerdx** [comment]
> @itsnicerdx 你好，请参考
> [issues/76](https://github.com/KingJA/LoadSir/issues/76)
> [issues/32](https://github.com/KingJA/LoadSir/issues/32)
明白了，每个activity or fragment 可以独立拥有一个Callback对象 感谢作者
