### ISSUE TITLE
xxxCallBack.class不存在

### ISSUE THREAD

**Issue by thkcheng** [KingJA/LoadSir#138]
进行了全局配置, 偶现进入页面时崩溃
日志显示的是  LoadingCallBack.class 不存在
明明已经进行了全局配置 而且是偶现不是必现的
测试时一天大概出现了四五次

**Comment by thkcheng** [comment]
又出现了~
日志：java.lang.IllegalArgumentException    The Callback (LoadingCallback) is nonexistent.
代码：先配置了全局的  因一直出现此问题 又在界面配置了一次  还是出现了
LoadSir loadSir = new LoadSir.Builder().addCallback(new LoadingCallback()).build();
        loadService = loadSir.getDefault().register(binding.rvActivities, (Callback.OnReloadListener) v -> {
            if (v.getId() == R.id.btnGoHome) {
                MainActivity.getInstance().goToHomeFragment();
            }
        });

**Comment by KingJA** [comment]
@thkcheng 你好，可以的话让我看下源码

**Comment by thkcheng** [comment]
// Application初始化的全局
    private void initLoadSir() {
        LoadSir.beginBuilder()
                .addCallback(new RetryCallback())
                .addCallback(new MineEmptyCallback())
                .addCallback(new LoadingCallback())
                .addCallback(new StoryEmptyCallback())
                .addCallback(new NoCommentCallback())
                .addCallback(new NoLightUpCallback())
                .addCallback(new MsgEmptyCallback())
                //.setDefaultCallback(LoadingCallback.class)
                .commit();
    }

// 在页面初始化时因为有时会出现找不到所以又初始化了一遍
LoadSir loadSir = new LoadSir.Builder().addCallback(new LoadingCallback()).build();
        loadService = loadSir.getDefault().register(binding.rvActivities, (Callback.OnReloadListener) v -> {
            if (v.getId() == R.id.btnGoHome) {
                MainActivity.getInstance().goToHomeFragment();
            }
        });

// 在请求接口之前调用
loadService.showCallback(LoadingCallback.class);

完事后就这还偶现不存在的情况

**Comment by KingJA** [comment]
@thkcheng 建议将全局初始化放在Application中
