### ISSUE TITLE
有没有人遇到当数据很快获取到时，不能显示成功布局，还是加载布局的情况？

### ISSUE THREAD

**Issue by jhwsx** [KingJA/LoadSir#159]
当应用去请求网络数据加载时，数据获取到后，调用展示成功布局，这时是正常显示的。
当第二次去请求数据时，这时得到的是缓存数据，迅速返回，仍然是调用展示成功布局，但是会出现仍然是加载中布局的情况。然后需要再点击一下加载布局，才会展示成功布局。

我现在的解决办法是增加一些延时，这样可以避免缓存数据立即返回。

**Comment by Ye83** [comment]
遇到了，同问，如何解决

**Comment by a5136683** [comment]
同求

**Comment by zizikoth** [comment]
因为DefaultCallback是使用Handler进行post到主线程中进行操作，如果直接手动调用showSuccess，会有一个时间差，导致先showSucess 然后又showDefaultCallback
进行延时或者修改源码将LoadService中initCallback的handler post操作去除

**Comment by a5136683** [comment]
感谢回复。我有尝试不设置DefaultCallback,但是这样会显示一个空白页。如果没有设置DefaultCallback的话，直接显示内容（即不展示callback）是否更加合理？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KingJA/LoadSir"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月19日(星期六) 凌晨4:05
收件人:&nbsp;"KingJA/LoadSir"<LoadSir@noreply.github.com&gt;;
抄送:&nbsp;"浪费青春"<540899652@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [KingJA/LoadSir] 有没有人遇到当数据很快获取到时，不能显示成功布局，还是加载布局的情况？ (#159)





 
因为DefaultCallback是使用Handler进行post到主线程中进行操作，如果直接手动调用showSuccess，会有一个时间差，导致先showSucess 然后又showDefaultCallback
 进行延时或者修改源码将LoadService中initCallback的handler post操作去除

**Comment by WinWang** [comment]
不考虑在界面延迟调用callback得情况下，暂时通过修改框架源码解决这个问题得方法是在LoadService中得initCallBack得方法中将设置defaultCallBack得方法中的Handler post设置直接去掉，直接调用即可 private void initCallback(LoadSir.Builder builder) {
        List<Callback> callbacks = builder.getCallbacks();
        final Class<? extends Callback> defalutCallback = builder.getDefaultCallback();
        if (callbacks != null && callbacks.size() > 0) {
            for (Callback callback : callbacks) {
                loadLayout.setupCallback(callback);
            }
        }
//        new Handler().post(new Runnable() {
//            @Override
//            public void run() {
//                if (defalutCallback != null) {
//                    loadLayout.showCallback(defalutCallback);
//                }
//            }
//        });

        /**
         * 省去Handler调用，不需要使用Handler发送，直接调用即可
         */
        if (defalutCallback != null) {
            loadLayout.showCallback(defalutCallback);
        }

    }

**Comment by AreYReady** [comment]
不想引入源代码，只需要这样调就可以避免这个问题。
view.post(new Runnable() {
            @Override
            public void run() {
                mLoadService.showSuccess();
            }
        });

**Comment by MrFishC** [comment]
@AreYReady  赞同，研究了几个小时，也是使用该方法处理。刚开始以为是自己代码使用出错了，使用新框架还是得看一下issues。
