### ISSUE TITLE
@Chinese people: Could you please write in English

### ISSUE THREAD

**Issue by Rainer-Lang** [KingJA/LoadSir#16]
I really would like to understand what's going on.... I'm very interested in this lib and I want to learn what I could do with it - and maybe I also could learn from your questions and ideas - or answer them in future.

If possible it would be really kind of you to write in English.
Thanks.

**Comment by AllanGuoxiLee** [comment]
https://translate.google.com

**Comment by Rainer-Lang** [comment]
Using a translation software for everything isn't a solution.
