### ISSUE TITLE
Suggestions for "Best Practice"

### ISSUE THREAD

**Issue by Rainer-Lang** [KingJA/LoadSir#17]
state: 27.09.2017 - PM 2:39 CEST

Only a collection of libs which could maybe used with LoadSir. I think it could be good to have examples for each of this use-cases.

For each use case I would suggest to make a separate activity in the sample app.

- [ ] https://github.com/mikepenz/FastAdapter - eg RecyclerView (loading data from REST (Retrofit)/database...getting no result, retry...get items and show RV)
- [ ] https://github.com/square/retrofit
- [ ] RecyclerView with SwipeRefreshLayout
- [ ] loading images with https://github.com/bumptech/glide
- [ ] usage with https://github.com/loregr/LGSnackbar for better SnackBar
- [ ] usage with https://github.com/mikepenz/Android-Iconics for better icon support

I will continue this list...

@KingJA Is this ok for you?

**Comment by KingJA** [comment]
@Rainer-Lang Good idea. It will be a long story.
