### ISSUE TITLE
the meaning of " Callback cloneCallback = callback.copy();"

### ISSUE THREAD

**Issue by softrice** [KingJA/LoadSir#20]
Why not use the “Callback cloneCallback = new CallBack();”.

**Comment by KingJA** [comment]
@softrice LoadSir do thar via **Prototype Pattern**. So that LoadSir could build unique Callback everytimme and own the unique layout, event. Is it clear?

**Comment by softrice** [comment]
Thx for your answer.And
![image](https://user-images.githubusercontent.com/10737613/30947420-415f7b0a-a3cf-11e7-99c4-bd60169e1306.png)
Are this method and "clone()" the same?
If so,why use this method ?

**Comment by KingJA** [comment]
@softrice [Prototype Pattern](https://github.com/KingJA/KPattern/blob/master/src/com/pattern/creational/prototype/Prototype.md)
