### ISSUE TITLE
add layout files/items for different states

### ISSUE THREAD

**Issue by Rainer-Lang** [KingJA/LoadSir#21]
I think this lib will be used quite for the states loading and showing some error with retry or empty.

Therefore it would be good to add generic layout items for 
- loading (ProgressBar/image, title, text)
- error (image, title, text, button for retry)
- empty (image, title, text, button for retry)
...of course with `Builder` pattern. :-)

This would be very convenient.

...and including default `Callback`s for these use cases.

**Comment by KingJA** [comment]
@Rainer-Lang You are right, some people like default Callbacks, just like custom View. But, What is the defference between LoadSir and other similar libs？
LoadSir  is a man with no face. He is freestyle. He has no eyes, no nose, no ears...He just has masks.
Perhaps I will add this feature one day, but not now. 
This issues will be opend for some days. Let‘s hear other sounds

**Comment by Rainer-Lang** [comment]
@KingJA It's about to make LoadSir more convenient to use - just out of the box. If someone would like to add own things (views/Callbacks whatever) this should be possible, of course. But there are cases when a developer just want to use a lib - without effort - then it's better if LoadSir has this already included. There are many other libs which have such views included. I think this could help LoadSir.

**Comment by KingJA** [comment]
@Rainer-Lang All right, You've got a point there. I will consider it, give me some time.
