### ISSUE TITLE
Difference between DefaultCallback and Callback?

### ISSUE THREAD

**Issue by Rainer-Lang** [KingJA/LoadSir#22]
I'm just wondering....
`setDefaultCallback(...)` vs `addCallback(...)`

- If I have at least one `Callback`, do I need a `DefaultCallback`? 
- What's the purpose of a `DefaultCallback`?

**Comment by KingJA** [comment]
@Rainer-Lang 
LoadSir is a man who has no face.
addCallback means to bring a mask to LoadSir.
setDefaultCallback means to put a mask(default) on LoadSir's face, this mask is the first mask on his face when LoadSir appear in front of people.
Is it clear?

**Comment by Rainer-Lang** [comment]
@KingJA I think it's clear. Maybe something for FAQ?

**Comment by KingJA** [comment]
@Rainer-Lang It's your show time, Rainer. I believe you are good at telling stories. :ghost:
