### ISSUE TITLE
 Caused by: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.

### ISSUE THREAD

**Issue by wenqian-cai-tuya** [KingJA/LoadSir#24]
按照你说的 显示ToolBar的话  “注册ToolBar以下的View，这样ToolBar就会被保留下”，如果是Activity没毛病，但如果是Fragment的话就会异常

**Comment by cai784921129** [comment]
LoadSir.getDefault().register(rootView.findViewById(R.id.contain), new Callback.OnReloadListener() {
            @Override
            public void onReload(View v) {
                onNetReload(v);
            }
        });


**xml：**
    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical"
        android:gravity="center"
        android:id="@+id/contain"
        >

        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="Success"
            android:textColor="#358c69"
            android:textSize="30sp"/>

        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="Fragment A content"/>

    </LinearLayout>

**Comment by wenqian-cai-tuya** [comment]
LoadSir.getDefault().register(rootView.findViewById(R.id.contain), new Callback.OnReloadListener() {
@override
public void onReload(View v) {
onNetReload(v);
}
});

xml：
  <android.support.v7.widget.Toolbar
        android:layout_width="match_parent"
        android:layout_height="?actionBarSize"
        app:title="fragmentA"
        ></android.support.v7.widget.Toolbar>

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical"
        android:gravity="center"
        android:id="@+id/contain"
        >

        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="Success"
            android:textColor="#358c69"
            android:textSize="30sp"/>

        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="Fragment A content"/>

    </LinearLayout>

**Comment by KingJA** [comment]
@cai784921129 谢谢，我也发现这个问题了，我会尽快修复。
新版本发布前我都会创建新版本预览版的分支，并加入改动的元素，请关注下。新版本预告请参考：https://github.com/KingJA/LoadSir/blob/master/docs/NextVersion.md

**Comment by KingJA** [comment]
@cai784921129 你好，新版本已修复该问题(善未优化)，https://github.com/KingJA/LoadSir/blob/v1.2.2-pre/app/src/main/java/sample/kingja/loadsir/target/KeepTitleFragment.java
可通过预览版尝试，https://github.com/KingJA/LoadSir/tree/v1.2.2-pre
，欢迎提出意见和建议。

**Comment by wenqian-cai-tuya** [comment]
有个问题请教一下，不明白为什么会出现这个异常 ，我看代码你在LoadSirUtil.java里已经写了
if (contentParent != null) {
            contentParent.removeView(oldContent);
        }
可为什么还会 出现The specified child already has a parent 这个异常

**Comment by KingJA** [comment]
@cai784921129 你好，v1.2.2里有保留标题的Demo，请问你使用的哪个版本？还有具体使用场景？提供代码会好些。

**Comment by wenqian-cai-tuya** [comment]
使用的 1.2.2-pre ，我看你在onCreateView里调用   rootView.removeView(contentView); 就解决了这个bug

**Comment by KingJA** [comment]
@cai784921129 恩，1.2.2的正式版已经发布，请更新。这是暂时的模板代码，还不够优化，我还会继续改进。
