### ISSUE TITLE
Placeholder explanation in readme

### ISSUE THREAD

**Issue by Rainer-Lang** [KingJA/LoadSir#3]
Maybe you should consider to explain the feature "placeholder" in the readme.
I know it's in your sample.

**Comment by KingJA** [comment]
It's a effect just like the library https://github.com/sharish/ShimmerRecyclerView works. Do you realy think I should explain it? I will try.

**Comment by KingJA** [comment]
@Rainer-Lang It's a effect just like the library https://github.com/sharish/ShimmerRecyclerView works. Do you realy think I should explain it? I will try.

**Comment by Rainer-Lang** [comment]
Maybe it's better to put a link to that lib in your readme.

**Comment by KingJA** [comment]
@Rainer-Lang Just include it,  your will like it.

**Comment by Rainer-Lang** [comment]
@KingJA YES - I do! 👍

**Comment by KingJA** [comment]
@Rainer-Lang And who you are, my friend, Could you send a email to me ? I gonna to sleep.

**Comment by Rainer-Lang** [comment]
@KingJA I already sent you an email at PM 5:21 (CEST). You didn't get it?
I used this email address: kingjavip@gmail.com
