### ISSUE TITLE
a question about layout

### ISSUE THREAD

**Issue by xiellml** [KingJA/LoadSir#32]
**CN**
@KingJA 你好, 我想问下为什么替换布局之后, 原来的View为什么不会报空指针, 也能设置数据, 加载成功后UI上的数据还能显示更改后的数据.

**En**
@KingJA Hi, I would like to know  the old View why not throw a  NullPointerException after replace layout, but also set the data, the UI after call showSuccess() can also display the changed data. (Why English is so awkward...)

**Comment by KingJA** [comment]
@sieml 因为每次register的时候，所有加载页的状态会被保留在[LoadLayout](https://github.com/KingJA/LoadSir/blob/master/loadsir/src/main/java/com/kingja/loadsir/core/LoadLayout.java#L22)中。这和Activity中findViewById的性质不一样。

**Comment by KingJA** [comment]
@sieml Thank you for using English so that my partner @Rainer-Lang  could know what happened. :ghost:

**Comment by xiellml** [comment]
@KingJA Thx. Yeah. I saw the boy's issue "@Chinese people", so...

**Comment by xiellml** [comment]
@KingJA Callback的深拷贝还没起到相关的作用是吗?  这么用有什么好处

**Comment by KingJA** [comment]
@sieml 你好，你说的深拷贝没起来相关作用什么意思呢?深拷贝的作用是从全局配置的Callback获取拷贝，这样全局配置的Callback就是原型，其它所有用到的地方都是复制品了，有自己的布局和事件了。

**Comment by xiellml** [comment]
@KingJA 原来如此, 明白了. 谢谢

**Comment by KingJA** [comment]
@sieml 不客气，感谢你的使用，LoadSir还在不断完善中，请关注github，近期将出一个关于LoadSir的最佳实践(LoadSir与其它主流库的结合使用，及几种较好的封装方式)。
