### ISSUE TITLE
The title bar is overwritten

### ISSUE THREAD

**Issue by xiellml** [KingJA/LoadSir#36]
@KingJA 在Fragment中keep title bar 之后, 标题栏被覆盖了, 由于使用了状态栏着色功能, 有啥办法解决么. 如图:
![image](https://user-images.githubusercontent.com/16185379/31041950-68c94524-a5d0-11e7-9622-48d323a505a5.png)

**Comment by KingJA** [comment]
@sieml 你好，解决了吗

**Comment by xiellml** [comment]
@KingJA 解决了
