### ISSUE TITLE
有一些问题，removeAllViews(); 导致 IllegalStateException

### ISSUE THREAD

**Issue by edifangyi** [KingJA/LoadSir#37]
![image](https://user-images.githubusercontent.com/12421552/31041926-c226eb5e-a5cf-11e7-90a7-a357dac011fe.png)

代码结构：
在Activity：
顺序

LoadSir loadSir = new LoadSir.Builder();
loadService = loadSir.register();

initRefreshLayout();
initRectclerView();
initAdapter();
loadData();//加载数据

其中

mRefreshLayout.setOnRefreshListener()  调用   loadData();

loadData()方法里，有 onSuccess - >在其中做了下列方法

if(responesList.siez()==0) {

     PostUtil.postCallbackDelayed(loadService, ErrorCallback.class);

}  else {

   mlist.clear();
   mlist.addAll(responesList);

   mAdapter.notifyDataSetChanged();

   mRefreshLayout.setRefreshing(false);

   mRecyclerView.loadMoreFinish(false, true);

   loadService.showSuccess();
}

在Activity顺序执行： loadData()==成功
在下拉刷新 第一次： loadData()==成功
在下拉刷新 第二次： loadData()==失败报错

**Comment by edifangyi** [comment]
是不是  loadService.showSuccess(); 只能执行一次 ๑乛◡乛๑

**Comment by KingJA** [comment]
@edifangyi 你好，如果你这是Demo的话，直接gmail发给我吧。

**Comment by edifangyi** [comment]
@KingJA 链接: https://pan.baidu.com/s/1i4E2wmh 密码: iiwm。。。邮件发给你被退回了
![image](https://user-images.githubusercontent.com/12421552/31313617-7559d97a-ac1a-11e7-8674-7bac4412bf0c.png)

**Comment by KingJA** [comment]
@edifangyi 你好，问题已查实。由于LoadSir的切换逻辑是removeView和addView方式，导致触发SwipeMenuRecyclerView的onDetachedFromWindow()方法->unregisterAdapterDataObserver()，导致下次刷新的时候会报new IllegalStateException("Observer " + observer + " was not registered.")异常。
为兼容与其它常用库的使用，LoadSir在v1.3.0版本不再removeView(SuccessView)，而采取GONE的方式隐藏。其它Callback的视图保持不变。
近期将发布新版本，感谢你的宝贵场景。

**Comment by edifangyi** [comment]
@KingJA 谢谢，麻烦了
