### ISSUE TITLE
使用LoadSir有时会抢占GridView的点击事件

### ISSUE THREAD

**Issue by jiangjunzailushang** [KingJA/LoadSir#40]

**Comment by KingJA** [comment]
@jiangjunzailushang 你好，请提供详细使用场景，或者最好是完整代码。

**Comment by jiangjunzailushang** [comment]
Fragment中使用
@Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.fragment_home, container, false);
        LoadSir loadSir = new LoadSir.Builder()
                .addCallback(new LoadingCallback())
                .addCallback(new EmptyCallback())
                .addCallback(new ErrorCallback())
                .addCallback(new PlaceholderCallback().copy())
                .setDefaultCallback(PlaceholderCallback.class)
                .build();
        mLoadService = loadSir.register(view, this);
        initID(view);
       return mLoadService.getLoadLayout();


Application中代码:
LoadSir.beginBuilder()
                .addCallback(new ErrorCallback())
                .addCallback(new EmptyCallback())
                .addCallback(new LoadingCallback())
                .addCallback(new PlaceholderCallback())
                .setDefaultCallback(LoadingCallback.class)
                .commit();
这样使用以后GridView子条目有时会无法点击,连续多次点击可能会响应事件,大多数情况下单次点击不能响应

**Comment by KingJA** [comment]
@jiangjunzailushang 你好，LoadSir的SuccessCallback的视图也就是原布局的视图没添加点击事情的。其它Callback才会触发点击事件。如果你能看到GridView说明你已经显示SuccessCallback了。如果你gmail提供完整代码.rar的话，我可以帮你一起分析下原因。
