### ISSUE TITLE
是用双层Fragment嵌套时 无法显示布局

### ISSUE THREAD

**Issue by jv-lee** [KingJA/LoadSir#41]
如题所示 在使用viewpager作为 主界面容器时 fragment中的子fragment 布局无法显示 ， 使用的是全局 LoadSir, 是在子Fragment中实例的 LoadService, 希望作者能解惑。

**Comment by KingJA** [comment]
@jv-lee 你好，如果能gmail提供完整代码.rar，效率会更高。

**Comment by jv-lee** [comment]
因为是项目代码  那我简单写个 demo  ，然后gmail提供给你 ，帮我看一下吧。

**Comment by jv-lee** [comment]
你好 暂时这边有些其他事情， 先保留这个问题吧， 谢谢了。

**Comment by EnzoEdison** [comment]
> @jv-lee 你好，如果能gmail提供完整代码.rar，效率会更高。

你好我也遇到了这个问题，我觉得不是嵌套的问题，是否viewpager+fragment必须在onCreateView中使用return loadService.getLoadLayout()作为根布局才能显示。能否让viewpager+fragment跟您的demo中的keeptitleFragment那种一样实现，onCreateView中返回默认view，在onViewCreated中处理注册。

**Comment by EnzoEdison** [comment]
> @jv-lee 你好，如果能gmail提供完整代码.rar，效率会更高。

我现在是fragment嵌套fragment，basefragment中的oncreateview返回默认根view，onviewcreate中注册loadsir，类似demo中的keeptitlefragment那种实现，结果发现子布局viewpager+fragment使用这种方法布局无法显示，必须使用在onCreateView中return loadService.getLoadLayout()才会显示。能否实现所有注册都是在viewoncreate中？还是我的代码处理错误了。
