### ISSUE TITLE
布局把整个界面全部都覆盖了，想留出一个搜索框

### ISSUE THREAD

**Issue by liguangze** [KingJA/LoadSir#42]
你好，我想在搜索栏显示，搜索不到显示为空，但是这个布局把整个界面全部都覆盖了，我想把搜索栏留出来，并且还有一个title，也给覆盖了，当数据为空的时候

**Comment by KingJA** [comment]
@liguangze 你好，如果你在Activity中保留，则register标题栏，搜索栏以外的布局即可，如果是在Fragment中保留，则参考Demo中的KeepTitle实例。

**Comment by liguangze** [comment]
不好意思，我是在activity中。 register是什么意思，我是直接用的  loadService.showCallback(EmptyCallback.class)方法

**Comment by KingJA** [comment]
@liguangze 

loadService = loadSir.register(contentView, new Callback.OnReloadListener() {
    @Override
    public void onReload(View v) {
        loadService.showCallback(LoadingCallback.class);
        // 重新加载逻辑
    }
});

contentView便是你布局里想要保留标题栏，搜索栏以外的内容布局。

**Comment by liguangze** [comment]
我明白你的意思了，contentView就是我想展示的布局了，但是contentView还有自己写上标题栏，搜索栏等，这样感觉很费事，有没有别的好办法，把空的布局弄成透明的，这样可以复用，因为标题栏上的文字，每个界面的标题都是不一样的，每次都要自己写一个contentView，这样子太麻烦了，或者每次都要找一次控件，有没有别的解决办法呢

**Comment by KingJA** [comment]
@liguangze 每次都重复操作是不怎么优雅，你可以抽取出BaseTitleActivity，可以参考我的案例。https://github.com/KingJA/LoadSirBestPractice/blob/master/app/src/main/java/sample/kingja/loadsirbestpractice/base/BaseTitleActivity.java

**Comment by liguangze** [comment]
@KingJA  谢谢
