### ISSUE TITLE
LoadSirHintCallback报错

### ISSUE THREAD

**Issue by HPLai** [KingJA/LoadSir#46]
hi，你好。LoadSirHintCallback这块好像有些变量啥的没有序列化，然后报错了。在demo，default LoadSir Callback这块

**Comment by KingJA** [comment]
@AndyGood 你好，你应该clone的是v1.3.0分支吧，这还不是正式的，只是新版本的测试版，新增的API还在调试和优化中。你可以重新clone下，我做了修改。
