### ISSUE TITLE
动画怎么添加，

### ISSUE THREAD

**Issue by liguangze** [KingJA/LoadSir#48]
Loading添加动画

loadService = loadSir.register(contentView, new Callback.OnReloadListener() {
@override
public void onReload(View v) {
loadService.showCallback(LoadingCallback.class);
// 重新加载逻辑
}
});

contentView
只能在这里自定义添加动画，假如我每个界面都用loading，每个界面都要从新写一遍吗

**Comment by KingJA** [comment]
@liguangze 你好，你可以看下v1.3.0 Demo里的**Animate Callback**，参考[AnimateCallback](https://github.com/KingJA/LoadSir/blob/v1.3.0/app/src/main/java/sample/kingja/loadsir/callback/AnimateCallback.java)，看是不是你要的效果

**Comment by liguangze** [comment]
@KingJA  OK完美
