### ISSUE TITLE
希望出个MAVEN的release

### ISSUE THREAD

**Issue by coldingcode** [KingJA/LoadSir#5]
如果可以出个maven的release，或者出个转换的话，我想我可以把这个jar用到我们的web页面中

**Comment by KingJA** [comment]
感谢你的建议，LoadSir发布的是基于Adndroid平台的aar。我不太明白你准备怎么用到web页面中？

**Comment by KingJA** [comment]
@EightMonth 感谢你的建议，LoadSir发布的是基于Adndroid平台的aar。我不太明白你准备怎么用到web页面中？

**Comment by 906798724** [comment]
请问，你这个用的是哪一个SDK版本，我看build.gradle中是rootproject.ext...
我是个新手，不太懂这个什么意思，能麻烦解释一下吗

**Comment by KingJA** [comment]
你能正常运行吧？这里使用的是全局配置方式。rootProject.ext对应的是项目根目录下config.gradle的ext变量。一般为了方便全局修改，采用这样的方式配置。具体你可以搜索下Android Gradle全局配置，了解下。

**Comment by KingJA** [comment]
@906798724 你好，你能正常运行吧？这里使用的是全局配置方式。rootProject.ext对应的是项目根目录下config.gradle的ext变量。一般为了方便全局修改，采用这样的方式配置。具体你可以搜索下Android Gradle全局配置，了解下。

**Comment by 906798724** [comment]
好的，谢谢 周磊 在2017年09月26日 09:45，KingJA 写道： @906798724 你好，你能正常运行吧？这里使用的是全局配置方式。rootProject.ext对应的是项目根目录下config.gradle的ext变量。一般为了方便全局修改，采用这样的方式配置。具体你可以搜索下Android Gradle全局配置，了解下。 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.
