### ISSUE TITLE
一个小问题

### ISSUE THREAD

**Issue by vangeldu** [KingJA/LoadSir#52]
想实现在loading时 不光能看到加载页面同时能看到content页面（即在loading和content同时能看到），但是这可能和这个库的设计理念有点违背了，看您的库是单页面的加载，我是想在加载时显示2种页面状态，但是目前没有想到很优雅的解决方式。如果有好的思路请告知，谢谢。

**Comment by KingJA** [comment]
@duweigang 你好，我非常理解你的需求，另一位读者也有同样的需求[#45](https://github.com/KingJA/LoadSir/issues/45)，这确实与LoadSir的设计思路不太符，但是既然你们有这个需求，并且这个需求是合理的，我会将其加入TODO。感谢你的使用。

**Comment by KingJA** [comment]
@duweigang 你好，[v1.3.2-pre](https://github.com/KingJA/LoadSir/tree/v1.3.2)已经实现该需求，可下载测试。在callback中override public boolean getSuccessVisible()返回为true即可。近期将整合issues发布新版本。

**Comment by vangeldu** [comment]
非常感谢，希望早日发布新版本

**Comment by KingJA** [comment]
@duweigang 你好，v1.3.2已发布。
