### ISSUE TITLE
提一个建议

### ISSUE THREAD

**Issue by wlingf** [KingJA/LoadSir#53]
在activity中 请求数据为空数据状态  加载回调布局页面会整个铺满屏幕  这样就会导致导航栏的部分被遮住了，最好修改为在导航栏下面

**Comment by wlingf** [comment]
@Override
    protected boolean onReloadEvent(final Context context, View view) {
        (view.findViewById(R.id.add_card_tv)).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                context.startActivity(new Intent(context, AddBankCardActivity.class).putExtra("isAdd", true));
            }
        });
        (view.findViewById(R.id.back)).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                context.finish();
            }
        });
        return true;
    }
在这个方法中无法finish

**Comment by KingJA** [comment]
@wlingf 
1.保留标题栏可以参考Demo中https://github.com/KingJA/LoadSir/blob/master/app/src/main/java/sample/kingja/loadsir/target/KeepTitleActivity.java。
2. ((Activity)context).finish();
