### ISSUE TITLE
关于最新版1.3.0的问题

### ISSUE THREAD

**Issue by weizai** [KingJA/LoadSir#55]
LoadSir作用在View上时，如果View设置了margin等属性，在LoadSir.showSuccess()后，这些属性会丢失, 1.2.0版本则正常。

**Comment by KingJA** [comment]
@weizai 你好，请用[v1.3.2](https://github.com/KingJA/LoadSir/tree/v1.3.2)的libaray再试下，如果有问题再告诉我。
