### ISSUE TITLE
提一个建议，reload的click事件

### ISSUE THREAD

**Issue by lh1241698502** [KingJA/LoadSir#56]
现在的reload的点击事件是设置在了整个的View上了（父布局的事件一直会被触发），建议在ids.xml中 添加 一个预先定义的id，用于设置reload的点击事件，可否这样：
        View reloadView = rootView.findViewById(R.id.reload_view);
        if (reloadView != null) {
            reloadView .setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    if (onReloadEvent(context, rootView)) {
                        return;
                    }
                    if (onReloadListener != null) {
                        onReloadListener.onReload(v);
                    }
                }
            });
        }

**Comment by KingJA** [comment]
@lh1241698502 感谢你的建议。
目前市面上有存在按钮点击和页面点击重试的场景，页面点击重试的出镜率会高点，因此LoadSir偏向页面点击，onReload便是这个需求的产物。当然如果希望按钮点击触发可以选择重写void onViewCreate(Context context, View view) ，从view中获取点击控件，自定义点击事件。LoadSir为了降低耦合，尽量避免预设任何设置。

**Comment by lh1241698502** [comment]
@KingJA Thanks！

**Comment by Puppy-Love** [comment]
@KingJA onViewCreate()重写了 点击事件通过接口回调出去 好像点击没效果

**Comment by Puppy-Love** [comment]
@KingJA  `    @Override
    protected void onViewCreate(Context context, View view) {
        super.onViewCreate(context, view);
        view.findViewById(R.id.btn_ok).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
//                if (onBtnClickListener!=null) {
                onBtnClickListener.onBtnClick(view);
//                }
                ArmsUtils.makeText(context,"跳转");
            }
        });
    }

    private OnBtnClickListener onBtnClickListener;

    public void setOnBtnClickListener(OnBtnClickListener listener) {
        this.onBtnClickListener = listener;
    }

    public interface OnBtnClickListener {
        void onBtnClick(View v);
    }

`

**Comment by KingJA** [comment]
@Puppy-Love 
你好，如果要自定义点击事件可以重写onReloadEvent实现。
```java
@Override
    protected boolean onReloadEvent(final Context context, View view) {
        Toast.makeText(context.getApplicationContext(), "Hello buddy! :p", Toast.LENGTH_SHORT).show();
        (view.findViewById(R.id.iv_gift)).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Toast.makeText(context.getApplicationContext(), "It's your gift! :p", Toast.LENGTH_SHORT).show();
            }
        });
        return true;
    }
```
如果不想局限在Callback里，想要在当前上下文实现点击逻辑可以通过动态修改Callback来实现。
```java
loadService.setCallBack(EmptyCallback.class, new Transport() {
   @Override
   public void order(Context context, View view) {
       TextView mTvEmpty = (TextView) view.findViewById(R.id.tv_empty);
       mTvEmpty.setText("fine, no data. You must fill it!");
   }
});
```
希望有帮到你。

**Comment by Puppy-Love** [comment]
@KingJA 谢谢 解决目前使用的场景
