### ISSUE TITLE
文档写的太简略了

### ISSUE THREAD

**Issue by HuRuWo** [KingJA/LoadSir#57]
正在使用，许多问题并没有讲的很清楚。需要打开代码自己寻找。比如如何做到只遮挡一部分，留出toolbar。文档中没有详讲，会让学习成本增加。

**Comment by KingJA** [comment]
@HuRuWo 你好，在[常见问题](https://github.com/KingJA/LoadSir/blob/master/docs/FAQ-cn.md)有关于你的需求。Demo中也有[Activity中保留标题栏](https://github.com/KingJA/LoadSir/blob/master/app/src/main/java/sample/kingja/loadsir/target/KeepTitleActivity.java)，[Fragment中保留标题栏](https://github.com/KingJA/LoadSir/blob/master/app/src/main/java/sample/kingja/loadsir/target/KeepTitleFragment.java)。
