### ISSUE TITLE
请教你个问题

### ISSUE THREAD

**Issue by ChiShengCan** [KingJA/LoadSir#58]
你的框架没有看的太明白，如何实现先呈现加载动画，然后判断是否数据为空，为空显示Empty，重现加载数据

**Comment by KingJA** [comment]
@ChiShengCan 你好，你可以先参考下Demo中的[Convertor转换器的使用](https://github.com/KingJA/LoadSir/blob/master/app/src/main/java/sample/kingja/loadsir/target/ConvertorActivity.java)
