### ISSUE TITLE
能把leakcanary集成去掉吗？

### ISSUE THREAD

**Issue by dazhiyu** [KingJA/LoadSir#59]
我也导入了leakcanary，然后我把自己导入的删掉后可以运行了，但是发现想用leakcanary还是用不了....
还要重新导入，陷入了死循环。

**Comment by KingJA** [comment]
@dazhiyu 你好，leakcanary只在Demo里存在依赖，library是没依赖的。你要使用LoadSir，直接gradle方式导入即可。

**Comment by dazhiyu** [comment]
哦哦
