### ISSUE TITLE
register 的View 如果是recyclerview 的问题

### ISSUE THREAD

**Issue by vangeldu** [KingJA/LoadSir#60]
register 的View 如果是recyclerview 的话，loadlayout在切换到success的时候，recyclerview虽然有高度，但是loadlayout的高度和宽度都没有。感觉和 view绘制有关

**Comment by vangeldu** [comment]
recyclerview父层是 swipeRefreshLayout

**Comment by KingJA** [comment]
@duweigang 请参考我的Demo：[LoadSirBestPractice](https://github.com/KingJA/LoadSirBestPractice/blob/master/app/src/main/java/sample/kingja/loadsirbestpractice/ui/follower/RepostoryActivity.java)，和你描述的差不多场景。如果还有疑问我们再详细谈论。

**Comment by vangeldu** [comment]
已经找到原因：关于swipeRefreshLayout嵌套recyclerview的问题时，loadLayout宽高为0的原因。

原因是我在register(recyclerview)【之前】，先行调用了`swipeRefreshLayout.setColorSchemeColors(Color.parseColor("#893712"));`这样一段代码。
而在如上方法的源码调用了如下方法：
```java
private void ensureTarget() {
        // Don't bother getting the parent height if the parent hasn't been laid
        // out yet.
        if (mTarget == null) {
            for (int i = 0; i < getChildCount(); i++) {
                View child = getChildAt(i);
                if (!child.equals(mCircleView)) {
                    mTarget = child;
                    break;
                }
            }
        }
    }
```
其中主要是确定了mTarget指向了recyclerview。

之后我调用register(recyclerview),然后按照View绘制流程，执行到`SwipeRefreshLayout.onMeasure()`中有这么一段代码：
 ```java
mTarget.measure(MeasureSpec.makeMeasureSpec(
                getMeasuredWidth() - getPaddingLeft() - getPaddingRight(),
                MeasureSpec.EXACTLY), MeasureSpec.makeMeasureSpec(
                getMeasuredHeight() - getPaddingTop() - getPaddingBottom(), MeasureSpec.EXACTLY));
```
因为此时的target是recyclerview，会计算recyclerview的宽高，但是因为SwipeRefreshLayout认为mTarget才是他的child，所以，之后在register了recyclerview之后，swipeRefreshLayout的mTarget按照正常逻辑应该是指向loadlayout，但是实际情况是继续指向recyclerview，整个过程loadlayout都没有执行过他自己的measure方法，所以宽高才是0。

当然如果不调用`setColorSchemeColors`这个方法，其实register和view的初始化调用顺序怎么写都没事，因为在绘制时，register之后是会指向正确的loadlayout。这里之所以会有问题，也是和SwipeRefreshLayout这个控件的measure方法实现有关。
可能有分析不到位的地方。。。（说这些是希望后来者别被这个调用顺序坑到），感觉作者可以加些说明关于调用的顺序方面。

**Comment by KingJA** [comment]
@duweigang 感谢你提供详细原因:smiley: ，我会将你的宝贵经验放入FAQ中。

**Comment by vangeldu** [comment]
@KingJA 不客气，感谢作者对开源做出的贡献

**Comment by KingJA** [comment]
@duweigang Thanks a lot. 欣慰.
