### ISSUE TITLE
当在Application里面不用默认的Loading状态时，用ViewPager加载多个fragment，每切换一个Fragment显示Loading状态，此时加载Loading那个圈很卡。

### ISSUE THREAD

**Issue by sy007** [KingJA/LoadSir#61]
在Application里面注释掉      
  LoadSir.beginBuilder()
                .addCallback(new ErrorCallback())
                .addCallback(new EmptyCallback())
                .addCallback(new LoadingCallback())
                .addCallback(new TimeoutCallback())
                .addCallback(new CustomCallback())
//                .setDefaultCallback(LoadingCallback.class)
                .commit();
FragmentA
    @Override
    public void loadNet() {
        PostUtil.postCallbackDelayed(mBaseLoadService, LoadingCallback.class);
    }
FragmentB
 @Override
    public void loadNet() {
        PostUtil.postCallbackDelayed(mBaseLoadService, LoadingCallback.class);
    }

**Comment by KingJA** [comment]
@sy007 你好，理论上是不应该存在卡的。请确定以下几点：
1.是不是最新版本v1.3.2？
2.换个手机测试。

**Comment by sy007** [comment]
你好,确实是手机问题 @KingJA -_-||
