### ISSUE TITLE
不兼容

### ISSUE THREAD

**Issue by wuh876** [KingJA/LoadSir#64]
这个库最低sdk要23吗？

**Comment by KingJA** [comment]
@wuh876 minSdkVersion = 14

**Comment by wuh876** [comment]
目标sdk 22不能用，提示
Error:(4) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Inverse'

**Comment by KingJA** [comment]
@wuh876 compileSdkVersion >= 23

**Comment by wuh876** [comment]
这个compileSdkVersion 低版本的就不行了

**Comment by KingJA** [comment]
@wuh876 因为库里使用到了26+的增强库的API，为了能适应和适配Android的更新，建议使用compileSdkVersion >= 23，如果由于特殊原因不能提高compileSdkVersion ，我会考虑更换API。
