### ISSUE TITLE
在fragment中有一些布局结构使用目前版本无法做到状态页面的切换

### ISSUE THREAD

**Issue by daiwenbo88** [KingJA/LoadSir#65]
作者好：我也通读了该项目源码 ，并且使用在项目中了，但是今天发现在fragment中 有一种布局结构无法达到各种状态页的替换 ，可能我脑子不好使 想半天 不知道怎么处理 希望作者您能看到 帮忙想想。 布局结构如下：
```
<FrameLayout>
            <LinearLayout vertical>
                      <EditText/>
                      <LinearLayout>...</LinearLayout>
                      <RecyclerView/>(这个是要 替换的View)
            </LinearLayout>
            <Button/>(最大的问题就是这个Button 是浮在最上面的)
</FrameLayout>
```

**Comment by daiwenbo88** [comment]
还是给图说明吧
[](http://on96fbw9r.bkt.clouddn.com/buju2.png)

**Comment by daiwenbo88** [comment]
[http://on96fbw9r.bkt.clouddn.com/buju2.png](url)

**Comment by KingJA** [comment]
@daiwenbo88 你好，能否详细描述下目前出现的问题？按钮被遮住了？还是其它？
BTW，图片可以直接拖到issue里的。

**Comment by daiwenbo88** [comment]
该布局是用在Fragment中的 主要是替换Button 下面那个RecyclerView 我知道demo 有一种KeepTitleFragment的案例 但是布局结构只嵌套了一个 LinearLayout  通过rootView.removeView(contentView);和getTitleLoadLayout(getContext(), rootView, titleBarView);是可以达到这个效果的  七牛那张图顶上有布局文件结构和说明 确实不太好办

**Comment by KingJA** [comment]
@daiwenbo88 
![image](https://user-images.githubusercontent.com/16667232/33119569-5c002db8-cfaa-11e7-9f96-b7d0115a7a7f.png)
我还是不是很理解你现在遇到了什么问题？是替换不了还是？

**Comment by daiwenbo88** [comment]
对 替换不了 制约因素 主要是用在Fragment中 不是Activity  因为需要返回 RooView

**Comment by daiwenbo88** [comment]
现在通过变通办法能达到 想要的效果 但是需要借助第三方
```
   @Override
    public void showEmpty() {
        View rootView = new EmptyCallback(mActivity, new Callback.OnReloadListener() {
            @Override
            public void onReload(View v) {

            }
        }).getRootView();//获取EmptyCallback 的RootView
        //借助第三方来实现 状态页的加载
        anadpter.setEmptyView(rootView);
    }
```

**Comment by KingJA** [comment]
@daiwenbo88  有可能是你调用姿势有问题，能把你原来有问题的调用过程，或者详细代码发我吗，如果是在项目中的话，能否做一个一个简单的能复现场景的Demo给我。

**Comment by daiwenbo88** [comment]
没问题  给个邮箱什么的 我这里做好了 就发给你帮忙看看

**Comment by KingJA** [comment]
@daiwenbo88 kingjavip@gmail.com

**Comment by daiwenbo88** [comment]
邮件以发送 期望回复

**Comment by daiwenbo88** [comment]
```
邮差小易温馨提示：建议您联系对方的管理员，请他高抬贵手帮您解决吧。
```
 您高抬贵手

**Comment by KingJA** [comment]
@daiwenbo88 已经发简书私信
