### ISSUE TITLE
关于ScrollView的滑动监听的问题

### ISSUE THREAD

**Issue by NeVaDaAAA** [KingJA/LoadSir#66]
作者您好，一直想找一个这样的库，目前来说，您的库是使用最方便的库，效果也不错。
我目前遇见了一个问题：
我的一个页面是做了一个类似于淘宝的Toolbar随ScrollView渐变颜色，目前出现了bug。

@Override
    public void onScrollChanged(GradationScrollView scrollView, int x, int y,
                                int oldx, int oldy) {
        // TODO Auto-generated method stub
        if (y <= 0) {   //设置标题的背景颜色
            goodsDetailToolbar.setBackgroundColor(Color.argb((int) 0, 255, 255, 255));
            goodsDetailTitle.setTextColor(Color.argb((int) 0, 255, 255, 255));
            goodsDetailFab.setVisibility(View.GONE);
        } else if (y > 0 && y <= height) { //滑动距离小于banner图的高度时，设置背景和字体颜色颜色透明度渐变
            float scale = (float) y / height;
            float alpha = (255 * scale);
            goodsDetailTitle.setTextColor(Color.argb((int) alpha, 1, 24, 28));
            goodsDetailToolbar.setBackgroundColor(Color.argb((int) alpha, 255, 255, 255));
            goodsDetailFab.setVisibility(View.GONE);
        } else {    //滑动到banner下面设置普通颜色
            goodsDetailToolbar.setBackgroundColor(Color.argb((int) 255, 255, 255, 255));
            goodsDetailToolbar.setAlpha(1);
            goodsDetailFab.setVisibility(View.VISIBLE);
            goodsDetailFab.setAlpha(0.75f);

        }
    }

height为Banner的高度。
当使用了您的控件，布局加载出来后，我滑动直接走了else这一块逻辑。请问该如何解决呢。
提前感谢！！！！！！！

**Comment by NeVaDaAAA** [comment]
LoadService loadService = LoadSir.getDefault().register(this, new Callback.OnReloadListener() {
        @Override
        public void onReload(View v) {
            // 重新加载逻辑
        }
    });
第一个参数我使用了This，页面的根布局，Scrollview均出现这种情况

**Comment by KingJA** [comment]
@NeVaDaAAA 你好，可否提供一个能重复场景的可调试的简易Demo给我，可以直接发你的github上，也可以发邮箱给我。这样解决问题会更加有效率。谢谢
