### ISSUE TITLE
建议在LoadService中加一个返回当前callback类型的api

### ISSUE THREAD

**Issue by typ0520** [KingJA/LoadSir#68]
有些时候需要知道当前的状态做不同的操作，如果加一个返回当前view状态的api，就不用自己在activity存状态了

**Comment by KingJA** [comment]
@typ0520 你好，你指返回当前Callback.class吗

**Comment by typ0520** [comment]
是的发自我的华为手机-------- 原始邮件 --------主题：Re: [KingJA/LoadSir] 建议在LoadService中加一个返回当前callback类型的api (#68)发件人：KingJA 收件人：KingJA/LoadSir 抄送：tong ,Mention @typ0520 你好，你指返回当前Callback.class吗

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/KingJA/LoadSir","title":"KingJA/LoadSir","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/KingJA/LoadSir"}},"updates":{"snippets":[{"icon":"PERSON","message":"@KingJA in #68: @typ0520 你好，你指返回当前Callback.class吗"}],"action":{"name":"View Issue","url":"https://github.com/KingJA/LoadSir/issues/68#issuecomment-354593410"}}}

**Comment by KingJA** [comment]
@typ0520 谢谢你的建议，很合理，我会在v1.3.5中增加相关API。近期发布

**Comment by typ0520** [comment]
👍   给你点赞
