### ISSUE TITLE
Fragment中如果用到了ButterKnife, 会产生异常

### ISSUE THREAD

**Issue by weizai** [KingJA/LoadSir#7]
@Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        rootView = inflater.inflate(getLayoutId(), container, false);
        unbinder = ButterKnife.bind(this, rootView);
        loadService = LoadSir.getDefault().register(rootView, new Callback.OnReloadListener() {
            @Override
            public void onReload(View v) {
                // retry logic
            }
        });
        return loadService.getLoadLayout();
    }

试下这段代码，然后在业务Fragment中通过@BindView(R.id.xxxx) View view1, 在调用view1的地方会产生空指针。

**Comment by KingJA** [comment]
@weizai 你好，我按你的场景做了一个简单的Demo，你可以看下，是可以正常配合ButterKnife使用的。https://github.com/KingJA/LoadSirDebug

**Comment by KingJA** [comment]
@weizai 如果有好的封装方式，也请分享下，谢谢哒

**Comment by weizai** [comment]
@KingJA  hi, demo看了下，问题出现在onCreateView中调用loadService.showCallback(EmptyCallback.class);, 改成loadService.showSuccess()就OK了。 考虑是EmptyCallback导致上一步的rootView被移除掉了?

**Comment by weizai** [comment]
希望能添加类似setCallBack(CallBack.class, Object bundle)方法，便于动态改变callback中view的属性

**Comment by KingJA** [comment]
@weizai 感谢你的建议，你能否能粗略提个PR，我大概理解下你的需求，或者详细描述下你的使用场景。

**Comment by weizai** [comment]
ok，我把场景详细描述下吧，比如在全局注册了一个EmptyCallback，在Fragment中执行A操作后显示空数据状态“没有数据哦”，执行B操作后显示空数据状态“暂无数据”，就是说注册的CallBack需要改变view状态，属性等. 我想通过传参数解决。loadsir可以通过注册2个不同的EmptyCallback解决，但感觉不太优雅。

**Comment by KingJA** [comment]
@weizai 你好，新版本增加了该功能，https://github.com/KingJA/LoadSir/blob/v1.2.2-pre/app/src/main/java/sample/kingja/loadsir/target/NormalActivity.java#L58-L64
可通过预览版尝试，https://github.com/KingJA/LoadSir/tree/v1.2.2-pre
，欢迎提出意见和建议。
