### ISSUE TITLE
列表加载问题

### ISSUE THREAD

**Issue by ghost** [KingJA/LoadSir#70]
作者你好,我有一个页面，只有一个recyclerview，支持底部加载更多，我先打开网络正常加载几页数据，这个时候recyclerview有几页数据了，然后断开网络，这个时候网络请求失败，走errorCallback.class,但是现在把整个页面都是error的页面，原先的recyclerview数据页不见了，请问这种情况应该如何处理，我希望加载更多的时候，即使发生错误，但是不替换掉原先已经加载出来的数据。谢谢

**Comment by KingJA** [comment]
@TonyJason 我的理解是，你的这个场景应该在返回数据的时候加个判断，如果没有数据成功加载过，返回错误码才显示错误界面，反之就return掉。
