### ISSUE TITLE
VIVO Y27Android 4.4.4,level 19报错java.io.FileNotFoundException:res/layout/abc_screen_simple.xml

### ISSUE THREAD

**Issue by MengkZhang** [KingJA/LoadSir#72]
VIVO Y27Android 4.4.4,level 19报错java.io.FileNotFoundException:res/layout/abc_screen_simple.xml

android.content.res.AssetManager.openXmlAssetNative(Native Method)
--
7 android.content.res.AssetManager.openXmlBlockAsset(AssetManager.java:488)
8 android.content.res.Resources.loadXmlResourceParser(Resources.java:2404)
9 android.content.res.Resources.loadXmlResourceParser(Resources.java:2377)

**Comment by KingJA** [comment]
@xiaolinzhang 你好，你提供的信息我无法判断是否是LoadSir造成的错误。请详细描述下报错时机，场景。
