### ISSUE TITLE
showSuccess下显示空白页

### ISSUE THREAD

**Issue by sososeen09** [KingJA/LoadSir#75]
调用loadService的showSuccess方法，页面还是显示空白，调用其它的CallBack则没问题，版本1.3.2

**Comment by sososeen09** [comment]
Bug找到了，我的布局是LinearLayout包含一个ToolBar和一个FrameLayout，其中FrameLayout是按照权重来设置高度的，改成match_parent就好了

**Comment by KingJA** [comment]
@sososeen09 OK

**Comment by ghost** [comment]
不支持权重设置的宽高吗？

**Comment by sososeen09** [comment]
目前看来是不支持的，权重只在LinearLayout中起作用，LoaderSir是把注册的布局存放在一个自定义的FrameLayout中了，所以不支持权重

**Comment by licoba** [comment]
我使用`ConstrainLayout`（toolbar+framelayout） 
注册contentLayout
`LoadSir.getDefault().register(frameLayout,...)`

调用showSuccess一样也是空白界面
