### ISSUE TITLE
Callback 复制

### ISSUE THREAD

**Issue by java02014** [KingJA/LoadSir#76]
你好，LoadLayout中的setupCallback，为什么要把传进来的Callback先拷贝在塞进集合？
![image](https://user-images.githubusercontent.com/7782392/37010948-e4fb6f36-2128-11e8-8be0-79d903a4ab17.png)

**Comment by KingJA** [comment]
@java02014 对各个Callback进行深克隆，这样Callback就可以独立控制。如果缺少这步，对一个Callback的修改将影响其它Callback。
