### ISSUE TITLE
请问如何获取全局添加的 Callback？

### ISSUE THREAD

**Issue by 6Weiqi** [KingJA/LoadSir#78]
我的情景是：
有一个全局的 LoadingCallback, 不希望整个布局可点击，只有布局中的按钮可点击，点击事件执行每个页面特定的逻辑。我想用获取全局的 Callback，在每个页面分别设置监听实现，但是好像没看到方法。

**Comment by 6Weiqi** [comment]
还有一个问题：在自定义 Callback 中加入 OnClickListener 或者 自定义接口属性，运行会崩溃

**Comment by 6Weiqi** [comment]
用动态修改 Callback 实现了，谢谢！

**Comment by KingJA** [comment]
good job.

**Comment by 6Weiqi** [comment]
刚在项目中用，exploring...
