### ISSUE TITLE
怎么自定义Callback里的按钮事件并传给外部使用？

### ISSUE THREAD

**Issue by magical-xu** [KingJA/LoadSir#84]
public class EmptyCallback extends com.kingja.loadsir.callback.Callback {

    private TextView mEmptyText;
    private RelationButton mEmptyButton;

    private String tips;
    private String buttonText;
    private View.OnClickListener buttonListener;

    public EmptyCallback(String emptyText, @Nullable String buttonText,
            @Nullable View.OnClickListener onClickListener) {
        this.tips = emptyText;
        this.buttonText = buttonText;
        this.buttonListener = onClickListener;
    }

    @Override
    protected boolean onReloadEvent(Context context, View view) {
        return super.onReloadEvent(context, view);
    }

    @Override
    protected int onCreateView() {
        return R.layout.empty_page_empty;
    }

    @Override
    protected void onViewCreate(Context context, View view) {
        super.onViewCreate(context, view);

        mEmptyText = view.findViewById(R.id.id_empty_text);
        mEmptyButton = view.findViewById(R.id.id_empty_button);

        if (!TextUtils.isEmpty(tips)) {
            mEmptyText.setText(tips);
        }

        if (!TextUtils.isEmpty(buttonText)) {
            mEmptyButton.setText(buttonText);
        }

        if (this.buttonListener != null) {
            mEmptyButton.setOnClickListener(buttonListener);
        }
    }
}

当我传给外边去处理点击事件就报错了

![_15243040014547](https://user-images.githubusercontent.com/15309220/39082932-a88ba35c-458d-11e8-932f-a8d886777f99.png)
![_15243040493339](https://user-images.githubusercontent.com/15309220/39082942-ca42a9dc-458d-11e8-9ca3-3a19102172a3.png)
![_15243044938218](https://user-images.githubusercontent.com/15309220/39082945-ce902a32-458d-11e8-8c35-20596a21760c.png)

setupCallback的时候为什么要 进行 copy? 比如我这里传了个listener 持有了外部的Activity 或 Fragment
由于序列化失败就抛异常了 导致 cloneCallback为空 setCallback时 报 NullPointerException

**Comment by KingJA** [comment]
@magical-xu 你好，可以尝试动态改变某个Callback
```java
loadService.setCallBack(EmptyCallback.class, new Transport() {
   @Override
   public void order(Context context, View view) {
       TextView mTvEmpty = (TextView) view.findViewById(R.id.tv_empty);
       mTvEmpty.setText("Fine, no data. You must fill it!");
   }
});
```
因为大多数场景的点击事件是重试，或者调至设置页面等，所以没有提供这类接口。
进行深复制是为了一次定义，多次应用。不同界面用到的Callback都是不一样的实例。如果不进行深复制，相当于单例。

**Comment by MakeCodeFly** [comment]
> public class EmptyCallback extends com.kingja.loadsir.callback.Callback {
> 
> ```
> private TextView mEmptyText;
> private RelationButton mEmptyButton;
> 
> private String tips;
> private String buttonText;
> private View.OnClickListener buttonListener;
> 
> public EmptyCallback(String emptyText, @Nullable String buttonText,
>         @Nullable View.OnClickListener onClickListener) {
>     this.tips = emptyText;
>     this.buttonText = buttonText;
>     this.buttonListener = onClickListener;
> }
> 
> @Override
> protected boolean onReloadEvent(Context context, View view) {
>     return super.onReloadEvent(context, view);
> }
> 
> @Override
> protected int onCreateView() {
>     return R.layout.empty_page_empty;
> }
> 
> @Override
> protected void onViewCreate(Context context, View view) {
>     super.onViewCreate(context, view);
> 
>     mEmptyText = view.findViewById(R.id.id_empty_text);
>     mEmptyButton = view.findViewById(R.id.id_empty_button);
> 
>     if (!TextUtils.isEmpty(tips)) {
>         mEmptyText.setText(tips);
>     }
> 
>     if (!TextUtils.isEmpty(buttonText)) {
>         mEmptyButton.setText(buttonText);
>     }
> 
>     if (this.buttonListener != null) {
>         mEmptyButton.setOnClickListener(buttonListener);
>     }
> }
> ```
> }
> 
> 当我传给外边去处理点击事件就报错了
> 
> ![_15243040014547](https://user-images.githubusercontent.com/15309220/39082932-a88ba35c-458d-11e8-932f-a8d886777f99.png)
> ![_15243040493339](https://user-images.githubusercontent.com/15309220/39082942-ca42a9dc-458d-11e8-9ca3-3a19102172a3.png)
> ![_15243044938218](https://user-images.githubusercontent.com/15309220/39082945-ce902a32-458d-11e8-8c35-20596a21760c.png)
> 
> setupCallback的时候为什么要 进行 copy? 比如我这里传了个listener 持有了外部的Activity 或 Fragment
> 由于序列化失败就抛异常了 导致 cloneCallback为空 setCallback时 报 NullPointerException

你解决了吗
