### ISSUE TITLE
如果Recyclerview的weight为1，showSuccess失败。

### ISSUE THREAD

**Issue by rainfoam** [KingJA/LoadSir#86]
Recyclerview下面还有一个Button,Recyclerview的weight为1，showSuccess时不加载为空。解决办法：在Recyclerview外面嵌套了一个LinearLayout,这个LinearLayout的weight为1，Recyclerview的width和height为Math可解决。

**Comment by KingJA** [comment]
@rainfoam LoadLayout 只获取控件的LayoutParams，你这种方式是中解决方法。

**Comment by feishuixiansheng** [comment]
<LinearLayout
        android:id="@+id/ll_listview"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="1">

        <android.support.v7.widget.RecyclerView
            android:id="@+id/rv_company_info"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />

    </LinearLayout>

    <TextView
        android:id="@+id/tv_sure"
        android:layout_width="match_parent"
        android:layout_height="40dp"
        android:layout_margin="15dp"
        android:background="@drawable/bg_button_solid_6484fb"
        android:gravity="center"
        android:text="确定"
        android:textColor="#ffffff"
        android:textSize="15dp" />

</LinearLayout>



我这样写的成功不了是为什么请看一下可以吗
