### ISSUE TITLE
和SmartRefreshLayout一起使用时的问题

### ISSUE THREAD

**Issue by superzhangbao** [KingJA/LoadSir#87]
不知道作者有没有使用过SmartRefreshLayout，一起使用的时候不显示内容，只显示success的，切换之后就不显示了
这是我的布局代码：
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <include layout="@layout/toobar" />
        <com.scwang.smartrefresh.layout.SmartRefreshLayout
            android:id="@+id/smart_refresh_layout"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:layout_behavior="@string/appbar_scrolling_view_behavior"
            app:srlDragRate="0.7"
            app:srlHeaderMaxDragRate="1.3"
            app:srlHeaderTriggerRate="0.5">

            <com.scwang.smartrefresh.header.MaterialHeader
                android:id="@+id/header"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                app:wshPrimaryColor="@color/white" />
            <FrameLayout
                android:id="@+id/fl_content"
                android:layout_width="match_parent"
                android:layout_height="match_parent">

                <android.support.v7.widget.RecyclerView
                    android:id="@+id/recycler_view"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:background="@color/white">
                </android.support.v7.widget.RecyclerView>

            </FrameLayout>

            <com.scwang.smartrefresh.layout.footer.ClassicsFooter
                android:layout_width="match_parent"
                android:layout_height="@dimen/dimen35"
                app:srlAccentColor="@color/toolbar_bg">

            </com.scwang.smartrefresh.layout.footer.ClassicsFooter>

        </com.scwang.smartrefresh.layout.SmartRefreshLayout>

</LinearLayout>

这是baseActivity里的代码：

private void addContent() {
        boolean needLoadService = isNeedLoadService();
        if (needLoadService) {
            FrameLayout flContent = rootView.findViewById(R.id.fl_content);
            if (flContent != null) {
                ButterKnife.bind(this, rootView);
                mBaseLoadService = LoadSir.getDefault().register(flContent, new Callback.OnReloadListener() {
                    @Override
                    public void onReload(View v) {
                        onNetReload(v);
                    }
                });
            }
            setContentView(rootView);
        }else {
            setContentView(rootView);
            ButterKnife.bind(this);
        }
    }

使用时：
mBaseLoadService.showCallback(ErrorCallback.class);
这时布局里framelayout包裹的区域就什么都不显示了，其他的地方用都是好好的。我也找不到原因了，还请作者帮忙看看

**Comment by AganCN** [comment]
遇到了同样的问题+1

**Comment by KingJA** [comment]
@superzhangbao @AganCN  
请参考：https://github.com/scwang90/SmartRefreshLayout/issues/245 ，不知道你们用的是否是兼容LoadSir的版本。

**Comment by superzhangbao** [comment]
@KingJA 应该不是兼容的问题，我用的是最新的版本，代码没有报错。只是不显示内容

**Comment by liuyouth** [comment]
@superzhangbao  同问 也遇到了类似问题

**Comment by liuyouth** [comment]
@superzhangbao  我想这个问题 应该可以关闭了
   android:layout_height="match_parent"
        android:layout_weight="1"
在布局中这么使用就可以了

**Comment by superzhangbao** [comment]
@liuyouth 请问
android:layout_height="match_parent"
android:layout_weight="1"这两个属性是使用在哪个控件上的

**Comment by liuyouth** [comment]
@superzhangbao 
我这边 是在Recyclerview 上面的
你那边 应该是这里的高度写成 match_parent
  <com.scwang.smartrefresh.header.MaterialHeader
            android:id="@+id/header"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:wshPrimaryColor="@color/white" />

**Comment by superzhangbao** [comment]
@liuyouth 谢谢  按照你说的可以了
