### ISSUE TITLE
个人意见

### ISSUE THREAD

**Issue by dengzhi00** [KingJA/LoadSir#89]
if (onBuildView(context) != null) {
            rootView = onBuildView(context);
        }
这样的写法是不是不好？

    @Override
    protected View onBuildView(Context context) {
        return new LinearLayout(context);
    }

**Comment by KingJA** [comment]
@dengzhi00 你好，能否说下理由，或者提供你的思路。

**Comment by dengzhi00** [comment]
这样会创建两次对象的

**Comment by KingJA** [comment]
@dengzhi00 明白了，感谢提醒。
