### ISSUE TITLE
线程安全问题?

### ISSUE THREAD

**Issue by JaydenFu** [KingJA/LoadSir#9]
PostUtil中的几个方法,都采用的new Handler() post方式,是为了线程安全吗?那应该new Handler(Looper.getMainLooper()).不然在子线程调用PostUtil中的方法会出错

**Comment by KingJA** [comment]
@JaydenFu 你好，PostUtil只是Sample工程里模拟网络访问的延迟方式，不是LoadSir进行线程安全的操作。LoadSir的线程安全操作请看https://github.com/KingJA/LoadSir/blob/master/loadsir/src/main/java/com/kingja/loadsir/core/LoadLayout.java#L59

**Comment by JaydenFu** [comment]
好的.多谢.
