### ISSUE TITLE
The Callback (EmptyCallback) is nonexistent.

### ISSUE THREAD

**Issue by MrX-Andy** [KingJA/LoadSir#94]
The Callback (EmptyCallback) is nonexistent.
按照发下初始化，为何会出现以上异常
`
mLoadService = LoadSir.getDefault().register(mRecyclerView, new Callback.OnReloadListener() {
            @Override
            public void onReload(View v) {
                new Thread(new Runnable() {
                    @Override
                    public void run() {
                        mLoadService.showCallback(LoadingCallback.class);
                        //do retry logic...
                        SystemClock.sleep(500);
                        //callback
                        mLoadService.showSuccess();
                    }
                }).start();
            }
        }).setCallBack(EmptyCallback.class, new Transport() {
            @Override
            public void order(Context context, View view) {
                TextView mTvEmpty = (TextView) view.findViewById(R.id.tv_empty);
                mTvEmpty.setText("fine, no data. You must fill it!");
            }
        });
        PostUtil.postCallbackDelayed(mLoadService, EmptyCallback.class);
`

**Comment by KingJA** [comment]
@goodfree 你好，请检查是否配置了EmptyCallback。

**Comment by goodfree** [comment]
已经解决了，谢谢
已替换成以下初始化方式
`mLoadSir = new LoadSir.Builder()
                .addCallback(new LoadingCallback())
                .addCallback(new ErrorCallback())
                .addCallback(new EmptyCallback())
                .setDefaultCallback(LoadingCallback.class)
                .build();`

**Comment by MrX-Andy** [comment]
> @goodfree 你好，请检查是否配置了EmptyCallback。

已解决，已替换成以下初始化方式
mLoadSir = new LoadSir.Builder()
                .addCallback(new LoadingCallback())
                .addCallback(new ErrorCallback())
                .addCallback(new EmptyCallback())
                .setDefaultCallback(LoadingCallback.class)
                .build();

**Comment by KingJA** [comment]
@goodfree 你好，你这种是单独配置方式，还有全局配置方式，可根据使用场景选择使用。

**Comment by jhwsx** [comment]
这边遇到了，当使用匿名内部类的方式进行 addCallback() 时，然后 showCallback 时，也会出现这样的错误。
