### ISSUE TITLE
结合AndroidUtilCode的沉浸式状态栏使用，RootView显示不正常

### ISSUE THREAD

**Issue by lvyandev** [KingJA/LoadSir#97]
项目中使用到[AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode)的沉浸式状态栏，
沉浸式代码设置如下
```
//设置Activity状态栏透明
BarUtils.setStatusBarAlpha(this)
//给RootView添加一个等于状态栏高度的Margin
activityRootView = window.decorView.findViewById<FrameLayout>(android.R.id.content).getChildAt(0)
BarUtils.addMarginTopEqualStatusBarHeight(activityRootView)
```

- **正常显示如下**
![ade91d12bb72fbec0ffe245156c3b8c3_](https://user-images.githubusercontent.com/18045999/46240320-3edfb280-c3d8-11e8-9a28-c33627ed1e50.jpg)

- **添加LoadService以后如下**
```
LoadSir.getDefault().register(this)
```
RootView上方多添加了已个状态栏高度

![8ee01dabe9c3bed414a63c2fb853dbed_](https://user-images.githubusercontent.com/18045999/46240389-3dfb5080-c3d9-11e8-8570-9277d17f36d0.jpg)

- 如果使用```BarUtils.subtractMarginTopEqualStatusBarHeight(activityRootView)```减掉Margin，又会导致原有的Margin也消失，RootView沉入状态栏
![5545d218a62b5f734146f1ddb5953857_](https://user-images.githubusercontent.com/18045999/46240391-42c00480-c3d9-11e8-9c22-be0436ba075a.jpg)

**Comment by candebbs** [comment]
解决了没有？

**Comment by KingJA** [comment]
@lvyandev @candebbs 两位好，1.3.8版本已经发布，已经解决margin重叠问题，欢迎更新使用，如果还是无法解决请继续留言，感谢使用和反馈 :)
