### ISSUE TITLE
activity 之间跳转经常会闪一下

### ISSUE THREAD

**Issue by 445759814** [KingJA/LoadSir#98]
就是下个界面都已经显示了，还闪现一下上个界面，注释调库相关的方法就没出现了。目前只在一加 9.0系统上发现，一加8.0的系统也没有此现象。

**Comment by KingJA** [comment]
@445759814 不好意思，目前其它机型没反馈过这个问题，身边也没一加9.0系统，暂不能调试你反映的问题，我会记下来。
