### ISSUE TITLE
只有cacamera的callback怎么解决

### ISSUE THREAD

**Issue by huanglinqing123** [KingJA/LoadSir#99]
![image](https://user-images.githubusercontent.com/14090613/46845234-1fe81400-ce0d-11e8-9774-bcba7415f15c.png)
![image](https://user-images.githubusercontent.com/14090613/46845241-2b3b3f80-ce0d-11e8-957c-2edd714bbd0a.png)
只有cacamera的callback怎么解决

**Comment by KingJA** [comment]
@huanglinqing123 你好，每个状态页面Callback都是需要自己创建的。不是库自带的。
